# Site settings

url: "http://www.albanseurat.com"
title: "Alban Seurat"
description: "Me myself and I"
keywords: "alban seurat, technology, computer science"
favicon: false
black-favicon: false
google-tracking-id: UA-16296685-1
disqus-shortname: false

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Career: 'career'
  Contact: 'contact'

intro-img: "/img/intro-bg.jpg"
background-img : "/img/bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Career variables

events:
  - image: "/img/career/kleis.webp"
    date: "September 2019 - Today"
    description: "Things you own end up owning you and vice versa"
  - image: "/img/career/octo.png"
    date: "September 2017 - August 2019"
    description: "Presenting Powerpoint to CxOs to talk about Conway's law"
  - image: "/img/career/nespresso.png"
    date: "Mars 2014 - August 2017"
    description: "Consulting to help people brew their coffee..."
  - image: "/img/career/tretonine.jpg"
    date: "February 2011 - November 2013"
    description: "My first experience creating an e-commerce startup"
  - image: "/img/career/experian.jpg"
    date: "April 2008 - January 2011"
    description: "<a href='http://www.experian.com/corporate/experian-decision-analytics.html' target='_new'>Experian</a> - Solution Architect designing scoring software for bank"
  - image: "/img/career/experian.jpg"
    date: "May 2004 - April 2008"
    description: "<a href='http://www.experian.com/corporate/experian-decision-analytics.html' target='_new'>Experian</a> - Development Team leader promoting agile methodology and coding C++ between 5 and 8PM..."
  - image: "/img/career/popfactory.jpg"
    date: "November 2000 - April 2004"
    description: "Trying small company, help a startup being valuable with my code"
  - image: "/img/career/experian.jpg"
    date: "April 1999 - October 2001"
    description: "<a href='http://www.experian.com/corporate/experian-decision-analytics.html' target='_new'>Experian</a> - First experience developing in C++ and Java back when Internet was running on 56k modem"
  - image: "/img/career/unice.png"
    date: "september 1997 - June 1999"
    description: "Universit√© Nice Sophia Antipolis @ <a href='http://iut.unice.fr/' target='_new'>Department of Computer Science</a>"
  - image: "/img/career/exel100.gif"
    date: "1989"
    description: "Write my first basic program in Exel 100 computer"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "linkedin"
    url: "http://ch.linkedin.com/in/AlbanSeurat"
  - title: "github"
    url: "https://github.com/AlbanSeurat"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
